

function generate(io::IO, libCvts::Union{Pair{<:AbstractString, Vector{Converted}}, Pair{Nothing, Vector{Converted}}}...; relto::String = ".")
	println(io, "# This file is automatically generated.  Do not edit.")
	println(io, "using CBinding: 𝐣𝐥")
	foreach(libCvts) do (lib, cvts)
		println(io)
		println(io, "𝐣𝐥.@cbindings", isnothing(lib) ? " " : " $(repr(String(lib))) ", "begin")
		generate(io, cvts, 1, relto = relto)
		println(io, "end")
	end
end


generate(io::IO, cvts::Vector{Converted}, indent::Int; relto::String = ".") = foreach(enumerate(cvts)) do (ind, cvt)
	ind > 1 && println(io, repeat('\t', indent))
	generate(io, cvt, indent, relto = relto)
end


function generate(io::IO, cvt::Converted, indent::Int; relto::String = ".")
	tabs = repeat('\t', indent)
	
	for (name, comment) in cvt.comments
		isempty(name) && continue
		
		comment = """
		𝐣𝐥.@doc \"\"\"
		$(rstrip(replace(replace(string(comment, expr = cvt.expr, relto = relto), '\\' => "\\\\"), '\"' => "\\\""), '\n'))
		\"\"\" $(name)
		"""
		
		println(io, tabs, rstrip(replace(comment, '\n' => "\n$(tabs)")))
	end
	
	exports = sort(collect(filter(str -> !startswith(str, '_'), keys(cvt.comments))))
	isempty(exports) || println(io, tabs, "export $(join(exports, ", "))")
	
	println(io, tabs, replace(cvt.expr, '\n' => "\n$(tabs)"))
end

